sources:
  - name: erp
    schema: erp_northwind
    description: Fonte de dados de vendas do SAP Northwind
    tables:
      - name: employees
        description: Tabela de funcionários
        columns:
          - name: employee_id
            tests:
              - unique
              - not_null
      - name: products
        description: Tabela de produtos
      - name: suppliers
        description: Tabela de fornecedores            
      - name: categories
        description: Tabela de categorias  
      - name: shippers
        description: Tabela de transportadores
      - name: customers
        description: Tabela de clientes
      - name: orders
        description: Tabela de ordens
      - name: order_details
        description: Tabela de ordens com pedidos